/**
 * Contract Library Module
 * Auto-generated from all CSV files in Contracts folder
 * Generated: 2025-10-21T07:12:30.041Z
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: node Tools/generate-contract-library.js
 */

const CONTRACT_LIBRARY = {
    "contract_extract_ai_synergy": {
        "name": "Extract Ai Synergy",
        "description": "Contract with 49 nodes, includes gate nodes, includes synergy nodes, runner type conditions, XY positioning",
        "csv": `"Node ID","Description","Effect Desc","Effect 1","Effect 2","Type","Color","X","Y","Width","Height","GateCondition","Connections"\r
"NODE002","Blast Through 
Entrance Area","+2 Grit","None;+;2;Grit","","Normal","Red","240.0","375.0","103.0","64.0","","NODE008"\r
"NODE001","Server Farm Entrance","+1 Risk
+1 Damage","None;+;1;Risk","None;+;1;Damage","Normal","Grey","-75.0","465.0","149.7","64.0","","NODE020,NODE002,NODE006,NODE007"\r
"NODE003","Gain Mainframe Access
and disable security","+1 Grit","None;+;1;Grit","","Normal","Blue","135.0","210.0","160.6","64.0","","NODE004"\r
"NODE004","Search for AI Core Location
in Room Database","+1 Grit","None;+;1;Grit","","Normal","Blue","405.0","210.0","184.8","64.0","","NODE022"\r
"NODE005","Sneak Into Core Room","+2 Veil","None;+;2;Veil","","Normal","Purple","915.0","225.0","154.4","60.0","","NODE012"\r
"NODE006","Distract Patrols,
then slip past","+2 Veil","None;+;2;Veil","","Normal","Purple","240.0","480.0","110.8","64.0","","NODE008"\r
"NODE007","Disable Back Entrance
Biometric Lock","+2 Veil","None;+;2;Veil","","Normal","Blue","210.0","585.0","153.6","64.0","","NODE008"\r
"NODE008","Main Building
(Locate AI Core)","+1 Risk
+1 Damage","None;+;1;Risk","None;+;1;Damage","Normal","Grey","450.0","465.0","114.7","80.0","","NODE009,NODE021,NODE011"\r
"NODE009","Take Down Security Guards
and copy Digital Map
from them","+2 Grit for each Muscle","RunnerType:Muscle;+;2;Grit","","Normal","Red","645.0","345.0","185.5","80.0","","NODE012"\r
"NODE010","Convince Caretaker to 
show you the way","+2 Veil","None;+;2;Veil","","Normal","Yellow","750.0","480.0","155.2","64.0","","NODE012"\r
"NODE011","Eavesdrop on
Technicians","+2 Veil for each Ninja","RunnerType:Ninja;+;2;Veil","","Normal","Purple","630.0","600.0","125.7","64.0","","NODE012"\r
"NODE012","AI Core Room","+1 Risk
+1 Damage","None;+;1;Risk","None;+;1;Damage","Normal","Grey","1005.0","480.0","100.7","64.0","","NODE013,NODE014"\r
"NODE013","Blow Up the Core","+3 Grit","None;+;3;Grit","","Normal","Red","1155.0","390.0","121.7","60.0","","NODE015"\r
"NODE014","Create Copy of AI
on Secure Shard","+3 Veil","None;+;3;Veil","","Normal","Blue","1170.0","570.0","123.3","64.0","","NODE015"\r
"NODE015","Escape after Core
Security Alert Triggered","+1 Risk
+1 Damage","None;+;1;Risk","None;+;1;Damage","Normal","Grey","1365.0","480.0","158.5","80.0","","NODE016,NODE017,NODE018"\r
"NODE016","Fight your way out","+1 Grit for each 
2 Muscle stat","RunnerStat:muscle>2;+;1;Grit","","Normal","Red","1590.0","330.0","126.4","64.0","","NODE019"\r
"NODE017","Stick to the Shadows
and Sneak Out","+1 Veil for each 2 Stealth Stat","RunnerStat:ninja>2;+;1;Veil","","Normal","Purple","1590.0","480.0","170.4","64.0","","NODE019"\r
"NODE018","Hack and take over
Security Drones","+1 Grit and +1 Veil for each 3 Hacker Stat","RunnerStat:hacker>3;+;1;Veil","RunnerStat:hacker>3;+;1;Grit","Normal","Blue","1590.0","615.0","168.1","80.0","","NODE019"\r
"NODE019","End","No Effect","None;+;0;Risk","","Normal","Grey","1860.0","480.0","80.0","60.0","",""\r
"NODE020","","≥ 4 Hacking","","","Gate","Blue","-30.0","300.0","80.0","60.0","RunnerStat:hacker;4","NODE003"\r
"NODE021","","≥ Face","","","Gate","Yellow","630.0","480.0","80.0","60.0","RunnerType:face;1","NODE010"\r
"NODE022","","≥1 Ninja","","","Gate","Purple","735.0","210.0","80.0","60.0","RunnerType:ninja;1","NODE005"\r
"NODE023","Versatile Approach","For Every Color Node Chosen:
+10% Reward","ColorForEach;%;10;Money","","Synergy","Green","90.0","0.0","176.1","64.0","",""\r
"NODE024","Tech Savvy","For every Blue Node Chosen: 
+10% Reward","NodeColor:Blue;%;10;Money","","Synergy","Green","315.0","0.0","173.4","64.0","",""\r
"NODE025","Risk Averse","For each pair of Damage and Risk prevented:
+15% Reward","RiskDamPair;%;15;Money","","Synergy","Green","540.0","0.0","194.8","80.0","",""\r
"NODE026","Money test node","Node effect description","None;+;200;Money","","Synergy","Purple","960.0","-75.0","134.5","60.0","",""\r
"NODE027","Money test node 2","Money 2","None;+;100;Money","","Normal","Red","975.0","0.0","127.2","60.0","",""`
    },
    "contract_gate_test": {
        "name": "Gate Test",
        "description": "Contract with 42 nodes, includes gate nodes, runner type conditions, XY positioning",
        "csv": `"Node ID","Description","Effect Desc","Effect 1","Effect 2","Type","Color","X","Y","Width","Height","GateCondition","Connections"\r
"NODE002","Blast Through 
Entrance Area","+2 Grit","None;+;2;Grit","","Normal","Red","240.0","375.0","103.0","64.0","","NODE008"\r
"NODE001","Server Farm Entrance","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","-75.0","465.0","149.7","64.0","","NODE020,NODE002,NODE006,NODE007,NODE024"\r
"NODE003","Gain Mainframe Access
and disable security","+1 Grit","None;+;1;Grit","","Normal","Blue","135.0","210.0","160.6","64.0","","NODE004"\r
"NODE004","Search for AI Core Location
in Room Database","Node effect description","None;+;1;Grit","","Normal","Blue","450.0","210.0","184.8","64.0","","NODE022"\r
"NODE005","Sneak Into Core Room","+2 Veil","None;+;2;Veil","","Normal","Purple","915.0","225.0","154.4","60.0","","NODE012"\r
"NODE006","Distract Patrols,
then slip past","+2 Veil","None;+;2;Veil","","Normal","Purple","240.0","480.0","110.8","64.0","","NODE008"\r
"NODE007","Disable Back Entrance
Biometric Lock","+2 Veil","None;+;2;Veil","","Normal","Blue","210.0","585.0","153.6","64.0","","NODE008"\r
"NODE008","Main Building
(Locate AI Core)","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","450.0","465.0","114.7","80.0","","NODE009,NODE021,NODE011"\r
"NODE009","Take Down Security Guards
and copy Digital Map
from them","+2 Grit for each Muscle","RunnerType:Muscle;+;2;Grit","","Normal","Red","645.0","345.0","185.5","80.0","","NODE012"\r
"NODE010","Convince Caretaker to 
show you the way","+2 Veil","None;+;2;Veil","","Normal","Yellow","750.0","480.0","155.2","64.0","","NODE012"\r
"NODE011","Eavesdrop on
Technicians","+2 Veil for each Ninja","RunnerType:Ninja;+;2;Veil","","Normal","Purple","630.0","600.0","125.7","64.0","","NODE012"\r
"NODE012","AI Core Room","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","1005.0","480.0","100.7","64.0","","NODE013,NODE014"\r
"NODE013","Blow Up the Core","+3 Grit","None;+;3;Grit","","Normal","Red","1155.0","390.0","121.7","60.0","","NODE015"\r
"NODE014","Create Copy of AI
on Secure Shard","+3 Veil","None;+;3;Veil","","Normal","Blue","1170.0","570.0","123.3","64.0","","NODE015"\r
"NODE015","Escape after Core
Security Alert Triggered","Node effect description","None;+;2;Risk","None;+;1;Damage","Normal","Grey","1365.0","480.0","158.5","64.0","","NODE016,NODE017,NODE018"\r
"NODE016","Fight your way out","+1 Grit for each 
3 Muscle stat","RunnerStat:muscle>3;+;1;Grit","","Normal","Red","1590.0","330.0","126.4","64.0","","NODE019"\r
"NODE017","Stick to the Shadows
and Sneak Out","+1 Veil for each 3 Stealth Stat","RunnerStat:stealth>3;+;1;Veil","","Normal","Purple","1590.0","480.0","170.4","64.0","","NODE019"\r
"NODE018","Hack and take over
Security Drones","+1 Grit and +1 Veil for each 5 Hacker Stat","RunnerStat:hacker>5;+;1;Veil","RunnerStat:hacker>5;+;1;Grit","Normal","Blue","1590.0","615.0","168.1","80.0","","NODE019"\r
"NODE019","End","No Effect","None;+;0;Risk","","Normal","Grey","1860.0","480.0","80.0","60.0","",""\r
"NODE020","","≥10 Hacking","","","Gate","Blue","-30.0","300.0","80.0","60.0","RunnerStat:hacker;10","NODE003"\r
"NODE021","","≥ Face","","","Gate","Yellow","630.0","480.0","80.0","60.0","RunnerType:face;1","NODE010"\r
"NODE022","","≥1 Ninja","","","Gate","Purple","735.0","210.0","80.0","60.0","RunnerType:ninja;1","NODE005"\r
"Gate1","New Node","Node effect description","None;+;0;Risk","","Normal","Green","-75.0","675.0","134.5","60.0","",""\r
"NODE024","","Node effect description","","","Gate","Green","210.0","690.0","134.5","60.0","Node:Gate1;0","NODE011"`
    },
    "contract_steal_rogue_ai_00": {
        "name": "Steal Rogue Ai 00",
        "description": "Contract with 40 nodes, includes gate nodes, runner type conditions, XY positioning",
        "csv": `"Node ID","Description","Effect Desc","Effect 1","Effect 2","Type","Color","X","Y","Width","Height","GateCondition","Connections"\r
"NODE002","Blast Through 
Entrance Area","+2 Grit","None;+;2;Grit","","Normal","Red","240.0","375.0","103.0","64.0","","NODE008"\r
"NODE001","Server Farm Entrance","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","-75.0","465.0","149.7","64.0","","NODE020,NODE002,NODE006,NODE007"\r
"NODE003","Gain Mainframe Access
and disable security","+1 Grit","None;+;1;Grit","","Normal","Blue","135.0","210.0","160.6","64.0","","NODE004"\r
"NODE004","Search for AI Core Location
in Room Database","Node effect description","None;+;1;Grit","","Normal","Blue","450.0","210.0","184.8","64.0","","NODE022"\r
"NODE005","Sneak Into Core Room","+2 Veil","None;+;2;Veil","","Normal","Purple","915.0","225.0","154.4","60.0","","NODE012"\r
"NODE006","Distract Patrols,
then slip past","+2 Veil","None;+;2;Veil","","Normal","Purple","240.0","480.0","110.8","64.0","","NODE008"\r
"NODE007","Disable Back Entrance
Biometric Lock","+2 Veil","None;+;2;Veil","","Normal","Blue","210.0","585.0","153.6","64.0","","NODE008"\r
"NODE008","Main Building
(Locate AI Core)","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","450.0","465.0","114.7","80.0","","NODE009,NODE021,NODE011"\r
"NODE009","Take Down Security Guards
and copy Digital Map
from them","+2 Grit for each Muscle","RunnerType:Muscle;+;2;Grit","","Normal","Red","645.0","345.0","185.5","80.0","","NODE012"\r
"NODE010","Convince Caretaker to 
show you the way","+2 Veil","None;+;2;Veil","","Normal","Yellow","750.0","480.0","155.2","64.0","","NODE012"\r
"NODE011","Eavesdrop on
Technicians","+2 Veil for each Ninja","RunnerType:Ninja;+;2;Veil","","Normal","Purple","630.0","600.0","125.7","64.0","","NODE012"\r
"NODE012","AI Core Room","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","1005.0","480.0","100.7","64.0","","NODE013,NODE014"\r
"NODE013","Blow Up the Core","+3 Grit","None;+;3;Grit","","Normal","Red","1155.0","390.0","121.7","60.0","","NODE015"\r
"NODE014","Create Copy of AI
on Secure Shard","+3 Veil","None;+;3;Veil","","Normal","Blue","1170.0","570.0","123.3","64.0","","NODE015"\r
"NODE015","Escape after Core
Security Alert Triggered","Node effect description","None;+;2;Risk","None;+;1;Damage","Normal","Grey","1365.0","480.0","158.5","64.0","","NODE016,NODE017,NODE018"\r
"NODE016","Fight your way out","+1 Grit for each 
3 Muscle stat","RunnerStat:muscle>3;+;1;Grit","","Normal","Red","1590.0","330.0","126.4","64.0","","NODE019"\r
"NODE017","Stick to the Shadows
and Sneak Out","+1 Veil for each 3 Stealth Stat","RunnerStat:stealth>3;+;1;Veil","","Normal","Purple","1590.0","480.0","170.4","64.0","","NODE019"\r
"NODE018","Hack and take over
Security Drones","+1 Grit and +1 Veil for each 5 Hacker Stat","RunnerStat:hacker>5;+;1;Veil","RunnerStat:hacker>5;+;1;Grit","Normal","Blue","1590.0","615.0","168.1","80.0","","NODE019"\r
"NODE019","End","No Effect","None;+;0;Risk","","Normal","Grey","1860.0","480.0","80.0","60.0","",""\r
"NODE020","","≥10 Hacking","","","Gate","Blue","-30.0","300.0","80.0","60.0","RunnerStat:hacker;10","NODE003"\r
"NODE021","","≥ Face","","","Gate","Yellow","630.0","480.0","80.0","60.0","RunnerType:face;1","NODE010"\r
"NODE022","","≥1 Ninja","","","Gate","Purple","735.0","210.0","80.0","60.0","RunnerType:ninja;1","NODE005"`
    },
    "contract_test_new": {
        "name": "Test New",
        "description": "Contract with 5 nodes, includes gate nodes, XY positioning",
        "csv": `"Node ID","Description","Effect Desc","Effect 1","Effect 2","Type","Color","X","Y","Width","Height","GateCondition","Connections"\r
"NODE001","Node 1","+2 grit","None;+;2;Grit","","Normal","Red","570.0","405.0","80.0","60.0","","NODE002,NODE003"\r
"NODE002","Node 3","+100 money","None;+;100;Money","","Normal","Purple","780.0","540.0","80.0","60.0","","NODE004"\r
"NODE003","Node 2","+2 dam +2 risk
","None;+;2;Damage","None;+;2;Risk","Normal","Grey","780.0","300.0","91.4","64.0","","NODE004"\r
"NODE004","Node 4","+2 veil","None;+;2;Veil","","Normal","Yellow","990.0","405.0","80.0","60.0","",""`
    },
    "contract_testcase": {
        "name": "Testcase",
        "description": "Contract with 50 nodes, includes gate nodes, includes synergy nodes, runner type conditions, XY positioning",
        "csv": `"Node ID","Description","Effect Desc","Effect 1","Effect 2","Type","Color","X","Y","Width","Height","GateCondition","Connections"\r
"NODE002","Blast Through 
Entrance Area","+2 Grit","None;+;2;Grit","","Normal","Red","225.0","360.0","103.0","64.0","","NODE008"\r
"NODE001","Server Farm Entrance","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","-75.0","465.0","149.7","64.0","","NODE020,NODE002,NODE006,NODE007,NODE028"\r
"NODE003","Gain Mainframe Access
and disable security","+1 Grit","None;+;1;Grit","","Normal","Blue","135.0","210.0","160.6","64.0","","NODE004"\r
"NODE004","Search for AI Core Location
in Room Database","+1 Grit","None;+;1;Grit","","Normal","Blue","405.0","210.0","184.8","64.0","","NODE022"\r
"NODE005","Sneak Into Core Room","+2 Veil","None;+;2;Veil","","Normal","Purple","915.0","225.0","154.4","60.0","","NODE012"\r
"NODE006","Distract Patrols,
then slip past","+2 Veil","None;+;2;Veil","","Normal","Purple","240.0","480.0","110.8","64.0","","NODE008"\r
"NODE007","Disable Back Entrance
Biometric Lock","+2 Veil","None;+;2;Veil","","Normal","Blue","210.0","585.0","153.6","64.0","","NODE008"\r
"NODE008","Main Building
(Locate AI Core)","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","450.0","465.0","114.7","80.0","","NODE009,NODE021,NODE011"\r
"NODE009","Take Down Security Guards
and copy Digital Map
from them","+2 Grit for each Muscle","RunnerType:Muscle;+;2;Grit","","Normal","Red","645.0","345.0","185.5","80.0","","NODE012"\r
"NODE010","Convince Caretaker to 
show you the way","+2 Veil","None;+;2;Veil","","Normal","Yellow","750.0","480.0","155.2","64.0","","NODE012"\r
"NODE011","Eavesdrop on
Technicians","+2 Veil for each Ninja","RunnerType:Ninja;+;2;Veil","","Normal","Purple","630.0","600.0","125.7","64.0","","NODE012"\r
"NODE012","AI Core Room","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","1005.0","480.0","100.7","64.0","","NODE013,NODE014"\r
"NODE013","Blow Up the Core","+3 Grit","None;+;3;Grit","","Normal","Red","1155.0","390.0","121.7","60.0","","NODE015"\r
"NODE014","Create Copy of AI
on Secure Shard","+3 Veil","None;+;3;Veil","","Normal","Blue","1170.0","570.0","123.3","64.0","","NODE015"\r
"NODE015","Escape after Core
Security Alert Triggered","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","1365.0","480.0","158.5","80.0","","NODE016,NODE017,NODE018"\r
"NODE016","Fight your way out","+1 Grit for each 
3 Muscle stat","RunnerStat:muscle>3;+;1;Grit","","Normal","Red","1590.0","330.0","126.4","64.0","","NODE019"\r
"NODE017","Stick to the Shadows
and Sneak Out","+1 Veil for each 3 Stealth Stat","RunnerStat:stealth>3;+;1;Veil","","Normal","Purple","1590.0","480.0","170.4","64.0","","NODE019"\r
"NODE018","Hack and take over
Security Drones","+1 Grit and +1 Veil for each 5 Hacker Stat","RunnerStat:hacker>5;+;1;Veil","RunnerStat:hacker>5;+;1;Grit","Normal","Blue","1590.0","615.0","168.1","80.0","","NODE019"\r
"NODE019","End","No Effect","None;+;0;Risk","","Normal","Grey","1860.0","480.0","80.0","60.0","",""\r
"NODE020","","≥10 Hacking","","","Gate","Blue","-30.0","300.0","80.0","60.0","RunnerStat:hacker;10","NODE003"\r
"NODE021","","≥ Face","","","Gate","Yellow","630.0","480.0","80.0","60.0","RunnerType:face;1","NODE010"\r
"NODE022","","≥1 Ninja","","","Gate","Purple","735.0","210.0","80.0","60.0","RunnerType:ninja;1","NODE005"\r
"NODE023","Versatile Approach","For Every Color Node Chosen:
+10% Reward","ColorForEach;%;10;Money","","Synergy","Green","90.0","0.0","176.1","64.0","",""\r
"NODE024","Tech Savvy","For every Blue Node Chosen: 
+10% Reward","NodeColor:Blue;%;10;Money","","Synergy","Green","315.0","0.0","173.4","64.0","",""\r
"NODE025","Risk Averse","For each pair of Damage and Risk prevented:
+15% Reward","RiskDamPair;%;15;Money","","Synergy","Green","540.0","0.0","194.8","80.0","",""\r
"NODE026","Money test node","Node effect description","None;+;200;Money","","Synergy","Purple","960.0","-75.0","134.5","60.0","",""\r
"NODE027","Money test node 2","Money 2","None;+;100;Money","","Normal","Red","1140.0","90.0","127.2","60.0","",""\r
"NODE028","Tthis is a test","+3 Grit","None;+;3;Grit","","Normal","Purple","210.0","705.0","94.5","60.0","","NODE021"`
    },
    "test123": {
        "name": "Test123",
        "description": "Contract with 3 nodes, includes gate nodes, includes synergy nodes, XY positioning",
        "csv": `"Node ID","Description","Effect Desc","Effect 1","Effect 2","Type","Color","X","Y","Width","Height","GateCondition","Connections"\r
"NODE001","New Node","Node effect description","","","Normal","Red","825.0","285.0","134.5","60.0","","NODE003,NODE002"\r
"NODE002","New Node","Node effect description","","","Synergy","Purple","1125.0","180.0","134.5","60.0","",""\r
"NODE003","Node 1","+3 grit für each 5 hacker stat","RunnerStat:Hacker>=5;+;3;Grit","","Normal","Grey","1080.0","420.0","164.4","60.0","",""`
    },
    "testestest": {
        "name": "Testestest",
        "description": "Contract with 52 nodes, includes gate nodes, includes synergy nodes, runner type conditions, XY positioning",
        "csv": `"Node ID","Description","Effect Desc","Effect 1","Effect 2","Type","Color","X","Y","Width","Height","GateCondition","Connections"\r
"NODE002","Blast Through 
Entrance Area","+2 Grit","None;+;2;Grit","","Normal","Red","240.0","375.0","103.0","64.0","","NODE008"\r
"NODE001","Server Farm Entrance","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","-75.0","465.0","149.7","64.0","","NODE020,NODE002,NODE006,NODE007"\r
"NODE003","Gain Mainframe Access
and disable security","+1 Grit","None;+;1;Grit","","Normal","Blue","135.0","210.0","160.6","64.0","","NODE004"\r
"NODE004","Search for AI Core Location
in Room Database","+1 Grit","None;+;1;Grit","","Normal","Blue","405.0","210.0","184.8","64.0","","NODE022"\r
"NODE005","Sneak Into Core Room","+2 Veil","None;+;2;Veil","","Normal","Purple","915.0","225.0","154.4","60.0","","NODE012"\r
"NODE006","Distract Patrols,
then slip past","+2 Veil","None;+;2;Veil","","Normal","Purple","240.0","480.0","110.8","64.0","","NODE008"\r
"NODE007","Disable Back Entrance
Biometric Lock","+2 Veil","None;+;2;Veil","","Normal","Blue","210.0","585.0","153.6","64.0","","NODE008"\r
"NODE008","Main Building
(Locate AI Core)","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","450.0","465.0","114.7","80.0","","NODE009,NODE021,NODE011"\r
"NODE009","Take Down Security Guards
and copy Digital Map
from them","+2 Grit for each Muscle","RunnerType:Muscle;+;2;Grit","","Normal","Red","645.0","345.0","185.5","80.0","","NODE012"\r
"NODE010","Convince Caretaker to 
show you the way","+2 Veil","None;+;2;Veil","","Normal","Yellow","750.0","480.0","155.2","64.0","","NODE012"\r
"NODE011","Eavesdrop on
Technicians","+2 Veil for each Ninja","RunnerType:Ninja;+;2;Veil","","Normal","Purple","630.0","600.0","125.7","64.0","","NODE012"\r
"NODE012","AI Core Room","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","1005.0","480.0","100.7","64.0","","NODE013,NODE014"\r
"NODE013","Blow Up the Core","+3 Grit","None;+;3;Grit","","Normal","Red","1155.0","390.0","121.7","60.0","","NODE015"\r
"NODE014","Create Copy of AI
on Secure Shard","+3 Veil","None;+;3;Veil","","Normal","Blue","1170.0","570.0","123.3","64.0","","NODE015"\r
"NODE015","Escape after Core
Security Alert Triggered","+2 Risk
+1 Damage","None;+;2;Risk","None;+;1;Damage","Normal","Grey","1365.0","480.0","158.5","80.0","","NODE016,NODE017,NODE018"\r
"NODE016","Fight your way out","+1 Grit for each 
3 Muscle stat","RunnerStat:muscle>3;+;1;Grit","","Normal","Red","1590.0","330.0","126.4","64.0","","NODE019"\r
"NODE017","Stick to the Shadows
and Sneak Out","+1 Veil for each 3 Stealth Stat","RunnerStat:ninja>3;+;1;Veil","","Normal","Purple","1590.0","480.0","170.4","64.0","","NODE019"\r
"NODE018","Hack and take over
Security Drones","+1 Grit and +1 Veil for each 5 Hacker Stat","RunnerStat:hacker>5;+;1;Veil","RunnerStat:hacker>5;+;1;Grit","Normal","Blue","1590.0","615.0","168.1","80.0","","NODE019"\r
"NODE019","End","No Effect","None;+;0;Risk","","Normal","Grey","1860.0","480.0","80.0","60.0","",""\r
"NODE020","","≥10 Hacking","","","Gate","Blue","-30.0","300.0","80.0","60.0","RunnerStat:hacker;10","NODE003"\r
"NODE021","","≥ Face","","","Gate","Yellow","630.0","480.0","80.0","60.0","RunnerType:face;1","NODE010"\r
"NODE022","","≥1 Ninja","","","Gate","Purple","735.0","210.0","80.0","60.0","RunnerType:ninja;1","NODE005"\r
"NODE023","Versatile Approach","For Every Color Node Chosen:
+10% Reward","ColorForEach;%;10;Money","","Synergy","Green","90.0","0.0","176.1","64.0","",""\r
"NODE024","Tech Savvy","For every Blue Node Chosen: 
+10% Reward","NodeColor:Blue;%;10;Money","","Synergy","Green","315.0","0.0","173.4","64.0","",""\r
"NODE025","Risk Averse","For each pair of Damage and Risk prevented:
+15% Reward","RiskDamPair;%;15;Money","","Synergy","Green","540.0","0.0","194.8","80.0","",""\r
"NODE026","Money test node","Node effect description","None;+;200;Money","","Synergy","Purple","960.0","-75.0","134.5","60.0","",""\r
"NODE027","Money test node 2","Money 2","None;+;100;Money","","Normal","Red","975.0","0.0","127.2","60.0","",""\r
"NODE028","^13123123123123123123123123","12312423451242451234523452524532453453245

s
dfgdfgdfgdfg","","","Normal","Red","1335.0","195.0","285.6","96.0","",""`
    }
};

// Helper function to get all contract keys
function getContractKeys() {
    return Object.keys(CONTRACT_LIBRARY);
}

// Helper function to get contract by key
function getContract(key) {
    return CONTRACT_LIBRARY[key];
}
